### ISSUE TITLE
Initial Setup Fails

### ISSUE THREAD

**Issue by mikerhyssmith** [Girish21/speed-metal-stack#1]
Hi 👋 

I followed the instructions to get this setup.

Ran `npx create-remix --template Girish21/speed-metal-stack` with no errors

Ran `npm run setup` with no errors.

And followed with 

`npm run dev`

I am then stuck with this error:

```
✘ [ERROR] [plugin server-bare-modules] Cannot find module '~/package.json'
Require stack:
- /Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js
- /Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/compiler.js
- /Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/cli/commands.js
- /Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/cli/run.js
- /Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/cli/index.js
- /Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/index.js
- /Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/cli.js

    app/components/footer.tsx:4:22:
      4 │ import GitHubSvg from '~/assets/icons/github.svg'
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:12:
      46 │       build.onResolve({
         ╵             ~~~~~~~~~

    at setup (/Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:13)
    at handlePlugins (/Users/mikesmith/Github/mikerhyssmith/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:842:23)
```

Any idea what might be happening here ?

Node version: v16.14.2
NPM versiomn: 8.5.0
OS: MacOS

**Comment by Girish21** [comment]
Hey, @mikerhyssmith, there seems to be an issue with Remix version `1.3.5` (https://github.com/remix-run/remix/issues/2691). Until that is fixed, can you downgrade all Remix packages to `1.3.4` and try again with a fresh install?

**Comment by Zloka** [comment]
Can confirm that downgrading worked in my case 🙂
